#almalinux is exactly same as centos and rhel. so we can use almalinux image instead of centos or rhel image.
#almalinux is exactly same as Redhat image, but completely free to use.
FROM almalinux:9
LABEL COURSE="Docker" \
TRAINER="Shivakumar" \
DURATION="10HRS" \
AUTHOR ="JOINDEVOPS"\

